### ISSUE TITLE
Add scan for ISBN-13: and ISBN-10:

### ISSUE THREAD

**Issue by stacey-quesnel** [dave-ruest/Bookmind#11]
May scan after ISBN-13: is added.
Some books also have ISBN-10: with ISBN-13: and the numbers that follow are not the same

Example: The Paris Affair by Teresa Grant.

Sam Francisco Lea Garchik

**Comment by dave-ruest** [comment]
I think the Paris affair should work now (that's "ISBN-10:") but yeah San Francisco is still broken (that's "ISBN 10:" i.e. a space instead of a dash).
